# <center>Games Stats</center>

In [1]:
#import
import plotly
from plotly import __version__
print (__version__)
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.plotly as py
import plotly.graph_objs as go

3.10.0

In [2]:
#Jupyter setup
init_notebook_mode(connected=True)

In [3]:
import pandas as pd

In [4]:
pubg = pd.read_csv('PXBG.csv')
#pubg.head(10)
df_pubg = pubg.apply(pd.to_numeric, errors='ignore')
df_new_pubg = df_pubg.head(10)

In [5]:
df_new_pubg.head(10)

   game_id     cause  end_time  game_id.1    result start_time      team
0        0      Draw  29:26:00          0  Turnover       0:00  opponent
1        1  Turnover  29:09:00          0     Clear   29:23:00      Navy
2        2     Clear  28:56:00          0      Goal   29:09:00      Navy
3        3      Draw  28:29:00          0      Goal       0:00      Navy
4        4      Draw  27:33:00          0      Shot       0:00      Navy
5        5      Shot  27:25:00          0      Goal   27:33:00      Navy
6        6      Draw  27:00:00          0      Goal       0:00      Navy
7        7      Draw  26:20:00          0      Shot       0:00      Navy
8        8      Shot  26:18:00          0      Goal   26:20:00      Navy
9        9      Draw  25:27:00          0      Goal       0:00      Navy

In [6]:
df_bar_pubg = df_pubg.head(30)

In [7]:
df_bar_pubg

,game_name,Navy_clear_attempts,Navy_draw_controls,Navy_failed_clears,Navy_fouls,Navy_free_positions,Navy_goals,Navy_ground_ball_pickups,Navy_possessions,Navy_shots,...,squad_RideDistance,squad_MoveDistance,squad_AvgWalkDistance,squad_AvgRideDistance,squad_LongestKill,squad_Heals,squad_Revives,squad_Boosts,squad_DamageDealt,squad_DBNOs
0,Army West Point,19,19,2,10,0,20,19,34,16,...,3751590.99,5194786.58,2626.97,4372.64,536.98,2186,234,1884,242132.73,1448
1,Army West Point,19,17,1,16,0,21,21,37,17,...,4295917.30,6051783.67,2422.48,6009.73,734.85,2041,276,2340,269795.75,1724
2,American,13,26,0,14,0,20,15,34,22,...,3935265.63,5589608.74,1871.89,3011.87,725.44,1766,210,2193,292977.07,1897
3,Boston College,21,7,3,12,0,5,17,22,17,...,2738998.00,3796916.00,2154.62,5578.41,587.28,1214,142,1252,181106.90,1057
4,Boston University,18,16,2,15,0,13,18,31,17,...,2347295.00,3220260.00,2098.47,5642.54,546.10,1245,120,923,160029.80,1077
5,Brown,24,21,2,24,0,18,15,31,21,...,3218436.00,4733977.00,2078.93,4414.86,1212.76,2023,195,2307,238640.00,1450
6,Bucknell,21,19,2,12,0,17,17,39,30,...,2057423.12,2883099.31,1664.77,3022.51,564.20,1274,133,1320,132008.88,775
7,Colgate,23,11,5,0,0,18,28,32,18,...,3586593.00,4854387.00,1635.86,4627.86,806.24,2199,163,1864,201659.00,1287
8,Florida,23,15,5,9,0,14,18,30,15,...,1054263.00,1550975.00,2207.61,4685.61,455.67,617,61,585,80498.73,513
9,Georgetown,22,16,3,8,0,16,19,31,16,...,2793909.91,4071039.87,1981.29,3635.28,546.95,1320,220,1338,123573.74,675
10,High Point,17,16,1,11,0,16,21,30,11,...,1795121.84,4248839.76,2191.49,2357.04,971.82,2616,341,2379,341578.55,2198
11,Holy Cross,20,16,1,13,0,22,21,35,22,...,2224095.54,3261630.99,1442.27,2484.46,436.70,1431,186,1142,126076.78,752
12,Lafayette,17,21,2,15,0,21,17,39,20,...,1878784.23,4044047.95,1815.85,1407.37,710.15,2667,417,2044,332970.41,2187
13,Lehigh,16,20,3,10,0,23,16,31,19,...,2063950.51,2786884.17,1256.33,1690.35,462.32,840,117,839,96604.62,553
14,Loyola,16,16,4,19,0,6,16,29,18,...,1391507.33,2015296.77,2354.22,5138.15,519.68,704,71,602,65327.24,436
15,Loyola,9,17,1,17,0,9,8,23,15,...,1872267.00,2502820.00,1958.24,5814.50,1001.90,488,126,1044,118409.80,680
16,Saint Joseph's,21,16,5,14,0,12,24,35,25,...,1313710.98,1964121.90,1717.99,5487.29,496.55,933,88,655,101034.30,606
17,Towson,19,18,2,20,0,14,21,38,15,...,1170384.39,1711422.05,1843.02,3272.59,610.58,566,120,650,103910.13,714
18,Villanova,21,15,2,13,0,14,17,35,17,...,1429614.00,2044366.00,2179.97,5069.55,548.12,623,111,889,80631.02,516
19,Virginia,18,16,5,19,0,12,18,32,18,...,2085239.00,3143840.85,1604.04,2581.89,453.66,997,172,940,153078.26,904
20,Virginia,14,19,1,22,0,12,12,33,17,...,2273010.51,3435396.93,1813.49,2815.27,627.89,1415,164,1663,194178.57,1195

In [8]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_clear_attempts'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_clear_attempts'],
        name= 'Opponent')

In [9]:
data = [trace1, trace2]
layout = go.Layout(title='Attempts',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [10]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_draw_controls'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_draw_controls'],
        name= 'Opponent')

In [11]:
data = [trace1, trace2]
layout = go.Layout(title='Draw controls',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [12]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_failed_clears'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_failed_clears'],
        name= 'Opponent')

In [13]:
data = [trace1, trace2]
layout = go.Layout(title='Failed_clears',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [14]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_fouls'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_fouls'],
        name= 'Opponent')

In [15]:
data = [trace1, trace2]
layout = go.Layout(title='Fouls',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [16]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_free_positions'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_free_positions'],
        name= 'Opponent')

In [17]:
data = [trace1, trace2]
layout = go.Layout(title='Free positions',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [18]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_goals'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_goals'],
        name= 'Opponent')

In [19]:
data = [trace1, trace2]
layout = go.Layout(title='Goals',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [20]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_ground_ball_pickups'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_ground_ball_pickups'],
        name= 'Opponent')

In [21]:
data = [trace1, trace2]
layout = go.Layout(title='Ground_ball pickups',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [22]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_possessions'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_possessions'],
        name= 'Opponent')

In [23]:
data = [trace1, trace2]
layout = go.Layout(title='Possessions',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [24]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_shots'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_shots'],
        name= 'Opponent')

In [25]:
data = [trace1, trace2]
layout = go.Layout(title='Shots',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [26]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_successful_clears'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_successful_clears'],
        name= 'Opponent')

In [27]:
data = [trace1, trace2]
layout = go.Layout(title='Successful clears',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [28]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_timeouts'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_timeouts'],
        name= 'Opponent')

In [29]:
data = [trace1, trace2]
layout = go.Layout(title='Timeouts',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')

In [30]:
trace1 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['Navy_turnovers'],
        name= 'Navy')

trace2 = go.Bar( 
        x = df_bar_pubg['game_name'],
        y = df_bar_pubg['opponent_turnovers'],
        name= 'Opponent')

In [31]:
data = [trace1, trace2]
layout = go.Layout(title='Turnovers',barmode='group')
fig = go.Figure(data=data, layout=layout)
iplot(fig, filename='grouped-bar')